site_name: acre
theme:
  name: material
  features:
    navigation.path
    navigation.tabs
    - content.code.copy
  palette:
    primary: deep-orange
    accent: deep-orange

nav:
  - Acre: index.md
  - Quickstart:
    - quickstart/index.md
    - quickstart/next.md
  - CLI:
    - CLI/index.md
    - init: CLI/init.md
    - run: CLI/run.md
  - Documentation:
    - doc/index.md
    - doc/configuration.md
    - doc/profiles.md
  - Terms and Definitions: terms.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://squidfunk.github.io/mkdocs-material/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
      separator: "-"
  - attr_list
  - def_list
  - tables
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - callouts
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true   
  - admonition
  - pymdownx.details
  - footnotes
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - md_in_html
  - mkdocs-click

plugins:
  - ezglossary:
      strict: false
      list_definitions: true
      list_references: true
      inline_refs: none
      tooltip: full
      use_default: false
      sections:
        - setting
        - term
        - demo
        - configuration
      section_config:
        - name: demo
          inline_refs: short
        - name: term
          inline_refs: short
      templates: docs/templates
      markdown_links: true
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 4
            show_source: false
            show_root_heading: true
            show_symbol_type_toc: true
            show_category_heading: true
            summary: true
